export enum FileType {
  METABO = 'METABO',
  ISTFEC = 'ISTFEC',
  ZONFEC = 'ZONFEC',
  IGAFEC = 'IGAFEC',
  CORTIS = 'CORTIS',
  GUTSYS = 'GUTSYS',
  VLSCFA = 'VLSCFA',
  IGGINT = 'IGGINT',
  UROGEN = 'UROGEN',
  INTLUC = 'INTLUC',
  AMMINO = 'AMMINO',
}
