export const AMMINO_EXPLANATIONS = [
  {
    id: 0,
    title: null,
    general: null,
    metaIds: '1-11',
  },
  {
    id: 1,
    title: null,
    general: null,
    metaIds: '12-21',
  },
  {
    id: 2,
    title: null,
    general: null,
    metaIds: '22-26',
  },
];

export const AMMINO_ELEMENTS_EXP = [
  {
    id: 1,
    name: 'exp.ammino.1.name',
    base: 'exp.ammino.1.base',
    hight: 'exp.ammino.1.hight',
    low: 'exp.ammino.1.low',
  },
  {
    id: 2,
    name: 'exp.ammino.2.name',
    base: 'exp.ammino.2.base',
    hight: 'exp.ammino.2.hight',
    low: 'exp.ammino.2.low',
  },
  {
    id: 3,
    name: 'exp.ammino.3.name',
    base: 'exp.ammino.3.base',
    hight: 'exp.ammino.3.hight',
    low: 'exp.ammino.3.low',
  },
  {
    id: 4,
    name: 'exp.ammino.4.name',
    base: 'exp.ammino.4.base',
    hight: 'exp.ammino.4.hight',
    low: 'exp.ammino.4.low',
  },
  {
    id: 5,
    name: 'exp.ammino.5.name',
    base: 'exp.ammino.5.base',
    hight: 'exp.ammino.5.hight',
    low: 'exp.ammino.5.low',
  },
  {
    id: 6,
    name: 'exp.ammino.6.name',
    base: 'exp.ammino.6.base',
    hight: 'exp.ammino.6.hight',
    low: 'exp.ammino.6.low',
  },
  {
    id: 7,
    name: 'exp.ammino.7.name',
    base: 'exp.ammino.7.base',
    hight: 'exp.ammino.7.hight',
    low: 'exp.ammino.7.low',
  },
  {
    id: 8,
    name: 'exp.ammino.8.name',
    base: 'exp.ammino.8.base',
    hight: 'exp.ammino.8.hight',
    low: 'exp.ammino.8.low',
  },
  {
    id: 9,
    name: 'exp.ammino.9.name',
    base: 'exp.ammino.9.base',
    hight: 'exp.ammino.9.hight',
    low: 'exp.ammino.9.low',
  },
  {
    id: 10,
    name: 'exp.ammino.10.name',
    base: 'exp.ammino.10.base',
    hight: 'exp.ammino.10.hight',
    low: 'exp.ammino.10.low',
  },
  {
    id: 11,
    name: 'exp.ammino.11.name',
    base: 'exp.ammino.11.base',
    hight: 'exp.ammino.11.hight',
    low: 'exp.ammino.11.low',
  },
  {
    id: 12,
    name: 'exp.ammino.12.name',
    base: 'exp.ammino.12.base',
    hight: 'exp.ammino.12.hight',
    low: 'exp.ammino.12.low',
  },
  {
    id: 13,
    name: 'exp.ammino.13.name',
    base: 'exp.ammino.13.base',
    hight: 'exp.ammino.13.hight',
    low: 'exp.ammino.13.low',
  },
  {
    id: 14,
    name: 'exp.ammino.14.name',
    base: 'exp.ammino.14.base',
    hight: 'exp.ammino.14.hight',
    low: 'exp.ammino.14.low',
  },
  {
    id: 15,
    name: 'exp.ammino.15.name',
    base: 'exp.ammino.15.base',
    hight: 'exp.ammino.15.hight',
    low: 'exp.ammino.15.low',
  },
  {
    id: 16,
    name: 'exp.ammino.16.name',
    base: 'exp.ammino.16.base',
    hight: 'exp.ammino.16.hight',
    low: 'exp.ammino.16.low',
  },
  {
    id: 17,
    name: 'exp.ammino.17.name',
    base: 'exp.ammino.17.base',
    hight: 'exp.ammino.17.hight',
    low: 'exp.ammino.17.low',
  },
  {
    id: 18,
    name: 'exp.ammino.18.name',
    base: 'exp.ammino.18.base',
    hight: 'exp.ammino.18.hight',
    low: 'exp.ammino.18.low',
  },
  {
    id: 19,
    name: 'exp.ammino.19.name',
    base: 'exp.ammino.19.base',
    hight: 'exp.ammino.19.hight',
    low: 'exp.ammino.19.low',
  },
  {
    id: 20,
    name: 'exp.ammino.20.name',
    base: 'exp.ammino.20.base',
    hight: 'exp.ammino.20.hight',
    low: 'exp.ammino.20.low',
  },
  {
    id: 21,
    name: 'exp.ammino.21.name',
    base: 'exp.ammino.21.base',
    hight: 'exp.ammino.21.hight',
    low: 'exp.ammino.21.low',
  },
  {
    id: 22,
    name: 'exp.ammino.22.name',
    base: 'exp.ammino.22.base',
    hight: 'exp.ammino.22.hight',
    low: 'exp.ammino.22.low',
  },
  {
    id: 23,
    name: 'exp.ammino.23.name',
    base: 'exp.ammino.23.base',
    hight: 'exp.ammino.23.hight',
    low: 'exp.ammino.23.low',
  },
  {
    id: 24,
    name: 'exp.ammino.24.name',
    base: 'exp.ammino.24.base',
    hight: 'exp.ammino.24.hight',
    low: 'exp.ammino.24.low',
  },
  {
    id: 25,
    name: 'exp.ammino.25.name',
    base: 'exp.ammino.25.base',
    hight: 'exp.ammino.25.hight',
    low: 'exp.ammino.25.low',
  },
];
