export const GUTSYS_TABLES = [
  {
    pageId: 0,
    sectionTitle: 'pdfpages.gutsysTables.0.sectionTitle',
    title: 'pdfpages.gutsysTables.0.title',
    elementsIds: '1-8',
    text1a: 'pdfpages.gutsysTables.0.text1a',
    text1: 'pdfpages.gutsysTables.0.text1',
    text2: 'pdfpages.gutsysTables.0.text2',
    text3: 'pdfpages.gutsysTables.0.text3',
    text4: 'pdfpages.gutsysTables.0.text4',
  },
  {
    pageId: 1,
    sectionTitle: 'pdfpages.gutsysTables.1.sectionTitle',
    title: 'pdfpages.gutsysTables.1.title',
    elementsIds: '9-18',
    text1a: 'pdfpages.gutsysTables.1.text1a',
    text1: 'pdfpages.gutsysTables.1.text1',
    text2: 'pdfpages.gutsysTables.1.text2',
    text3: 'pdfpages.gutsysTables.1.text3',
  },
  {
    pageId: 2,
    sectionTitle: 'pdfpages.gutsysTables.2.sectionTitle',
    title: 'pdfpages.gutsysTables.2.title',
    elementsIds: '19-28',
    text1a: 'pdfpages.gutsysTables.2.text1a',
    text1: 'pdfpages.gutsysTables.2.text1',
    text2: 'pdfpages.gutsysTables.2.text2',
    text3: 'pdfpages.gutsysTables.2.text3',
  },
  {
    pageId: 3,
    sectionTitle: 'pdfpages.gutsysTables.3.sectionTitle',
    title: 'pdfpages.gutsysTables.3.title',
    elementsIds: '29-30',
    text1a: 'pdfpages.gutsysTables.3.text1a',
    text1: 'pdfpages.gutsysTables.3.text1',
    text2: 'pdfpages.gutsysTables.3.text2',
    text3: 'pdfpages.gutsysTables.3.text3',
  },
  {
    pageId: 4,
    sectionTitle: 'pdfpages.gutsysTables.4.sectionTitle',
    title: 'pdfpages.gutsysTables.4.title',
    elementsIds: '31-32',
    text1a: 'pdfpages.gutsysTables.4.text1a',
    text1: 'pdfpages.gutsysTables.4.text1',
    text2: 'pdfpages.gutsysTables.4.text2',
    text3: 'pdfpages.gutsysTables.4.text3',
  },
];
