export const GUTSYS_NAMES = {
  '1': 'Bacillus cereus',
  '2': 'Campylobacter spp',
  '3': 'Clostridium difficile',
  '4': 'Escherichia coli produttore di Shiga tossine STEC',
  '5': 'Escherichia coli O157',
  '6': 'Salmonella spp',
  '7': 'Shigella spp',
  '8': 'Yersinia enterocolitica',
  '9': 'Aspergillus spp',
  '10': 'Candida albicans',
  '11': 'Candida dubliniensis',
  '12': 'Candida glabrata',
  '13': 'Candida krusei',
  '14': 'Candida lusitaniae',
  '15': 'Candida parapsilosis',
  '16': 'Candida tropicalis',
  '17': 'Fusarium spp',
  '18': 'Talaromyces marneffei (Penicillium)',
  '19': 'Citrobacter freundii',
  '20': 'Clostridium perfringens',
  '21': 'Klebsiella pneumoniae',
  '22': 'Morganella morganii',
  '23': 'Proteus mirabilis',
  '24': 'Providencia spp',
  '25': 'Pseudomonas aeruginosa',
  '26': 'Serratia marcescens',
  '27': 'Staphylococcus aureus',
  '28': 'Streptococcus pyogenes',
  '29': 'Bacteroides fragilis',
  '30': 'Prevotella spp',
  '31': 'Bifidobacterium spp',
  '32': 'Lactobacillum spp',
  '33': 'Ancylostoma spp',
  '34': 'Ascaris spp',
  '35': 'Blastocystis hominis',
  '36': 'Cryptosporidium spp',
  '37': 'Cyclospora cayetanensis',
  '38': 'Dientamoeba fragilis',
  '39': 'Enterobius vermicularis',
  '40': 'Enterocytozoon spp Encephalitozoon spp',
  '41': 'Enthamoeba histolytica',
  '42': 'Giardia intestinalis',
  '43': 'Hymenolepis spp',
  '44': 'Necator americanus',
  '45': 'Strongyloides spp',
  '46': 'Taenia spp',
  '47': 'Trichuris trichiura',
  '48': 'Caspofun (CAS 5 μg)',
  '49': 'Fluconazole (FLU 25 μg)',
  '50': 'Posoconazole (POS 5 μg)',
  '51': 'Voriconazole (VO 1 μg)3',
  '52': 'Amphotericin (AMB 20 μg)',
  '53': 'Ketokonazole (KCA 10 μg)',
  '54': 'Flucytosine (AFY 1 μg)',
  '55': 'Nystatin (NY 100 μg)',
  '56': 'Cannella',
  '57': 'Njauli',
  '58': 'Salvia',
  '59': 'Ginepro',
  '60': 'Cajeput',
  '61': 'Chiodi di garofano',
  '62': 'Lavanda',
  '63': 'Santoreggia',
  '64': 'Melissa',
  '65': 'Rosmarino',
  '66': 'Origano',
  '67': 'Pino silvestre',
  '68': 'Melaleuca',
  '69': 'Eucalipto',
  '70': 'Timo',
  '71': 'Zenzero',
  '72': 'Ciprofloxacin (CIP 5 μg)',
  '73': 'Doxycicline (DXT 30 μg)',
  '74': 'Fosfomycin (FOS 50 μg)',
  '75': 'Levofloxacin (LEV 5 μg)',
  '76': 'Metronidazole (MTZ 50 μg)',
  '77': 'Moxifloxacin (MXF 5 μg)',
  '78': 'Nitrofurantoin (F 100 μg)',
  '79': 'Trimethoprim-Sulfamethoxa',
  '80': '0',
  '81': '7',
  '82': 'POLTACEA',
  '83': 'MARRONE',
  '84': 'Aureobasidium pullulans',
  '85': 'Blastoschizomyces capitatus',
  '86': 'Candida albicans',
  '87': 'Candida apicola',
  '88': 'Candida ciferrii',
  '89': 'Candida colliculosa',
  '90': 'Candida famata',
  '91': 'Candida glabrata',
  '92': 'Candida guilliermondii',
  '93': 'Candida intermedia',
  '94': 'Candida kefyr',
  '95': 'Candida krusei',
  '96': 'Candida lambica',
  '97': 'Candida lusitaniae',
  '98': 'Candida marina',
  '99': 'Candida parapsilosis',
  '100': 'Candida rugosa',
  '101': 'Candida stellatoidea',
  '102': 'Candida tropicalis',
  '103': 'Candida utilis',
  '104': 'Candida zeylanoides',
  '105': 'Cryptococcus albidus',
  '106': 'Cryptococcus humicoluse',
  '107': 'Cryptococcus laurentii',
  '108': 'Cryptococcus ',
  '109': 'Cryptococcus terreus',
  '110': 'Cryptococcus uniguttulatus',
  '111': 'Geotrichium spp.',
  '112': 'Hanseniaspora guilliermondii/uvarum',
  '113': 'Hansenula wingei',
  '114': 'Kluyveromyces spp.',
  '115': 'Pichia anomala',
  '116': 'Prototheca wickerhamii',
  '117': 'Prototheca zopfii',
  '118': 'Rhodotorula glutinis',
  '119': 'Rhodotorula minuta',
  '120': 'Rhodotorula rubra',
  '121': 'Saccharomyces cerevisiae',
  '122': 'Sporobolomyces salmonicolor',
  '123': 'Trichosporon beigelii',
  '124': 'Yarrowia lipolytica',
};
