export const METABOLOMICS_EXPLANATIONS = [
  {
    id: 0,
    title: 'exp.generic.glicolitico.title',
    general: 'exp.generic.glicolitico.text',
    metaIds: '1-2',
  },
  {
    id: 1,
    title: 'exp.generic.chetoni.title',
    general: 'exp.generic.chetoni.text',
    metaIds: '3-7',
  },
  {
    id: 2,
    title: 'exp.generic.mitocondriali.title',
    general: 'exp.generic.mitocondriali.text',
    metaIds: '8-15',
  },
  {
    id: 3,
    title: 'exp.generic.neurotrasmettitori.title',
    general: 'exp.generic.neurotrasmettitori.text',
    metaIds: '16-28',
  },
  {
    id: 4,
    title: 'exp.generic.intestinale.title',
    general: 'exp.generic.intestinale.text',
    metaIds: '29-45',
  },
  {
    id: 5,
    title: 'exp.generic.ossalati.title',
    general: 'exp.generic.ossalati.text',
    metaIds: '46-48',
  },
  {
    id: 6,
    title: 'exp.generic.nutrizionali.title',
    general: 'exp.generic.nutrizionali.text',
    metaIds: '49-55',
  },
  {
    id: 7,
    title: 'exp.generic.piramidina.title',
    general: 'exp.generic.piramidina.text',
    metaIds: '56-57',
  },
  {
    id: 8,
    title: 'exp.generic.detossificazione.title',
    general: 'exp.generic.detossificazione.text',
    metaIds: '58-61',
  },
  {
    id: 9,
    title: 'exp.generic.amminoacidi.title',
    general: 'exp.generic.amminoacidi.text',
    metaIds: '62-70',
  },
];

export const METABO_ELEMENTS_EXP = [
  {
    id: 1,
    name: 'exp.piruvico.name',
    base: 'exp.piruvico.base',
    hight: 'exp.piruvico.hight',
  },
  {
    id: 2,
    name: 'exp.lattico.name',
    base: 'exp.lattico.base',
    hight: 'exp.lattico.hight',
  },
  {
    id: 3,
    name: 'exp.acidosebacico.name',
    base: 'exp.acidosebacico.base',
    hight: 'exp.acidosebacico.hight',
  },
  {
    id: 4,
    name: 'exp.acidoadipico.name',
    base: 'exp.acidoadipico.base',
    hight: 'exp.acidoadipico.hight',
  },
  {
    id: 5,
    name: 'exp.acidosuberico.name',
    base: 'exp.acidosuberico.base',
    hight: 'exp.acidosuberico.hight',
    low: 'exp.acidosuberico.low',
  },
  {
    id: 6,
    name: 'exp.etilmalonico.name',
    base: 'exp.etilmalonico.base',
    hight: 'exp.etilmalonico.hight',
    low: 'exp.etilmalonico.low',
  },
  {
    id: 7,
    name: 'exp.acido3idrossibutirrico.name',
    base: 'exp.acido3idrossibutirrico.base',
    hight: 'exp.acido3idrossibutirrico.hight',
    low: 'exp.acido3idrossibutirrico.low',
  },
  {
    id: 8,
    name: 'exp.acidocitrico.name',
    base: 'exp.acidocitrico.base',
    hight: 'exp.acidocitrico.hight',
    low: 'exp.acidocitrico.low',
  },
  {
    id: 9,
    name: 'exp.acidoaconitico.name',
    base: 'exp.acidoaconitico.base',
    hight: 'exp.acidoaconitico.hight',
    low: 'exp.acidoaconitico.low',
  },
  {
    id: 10,
    name: 'exp.acidoisocitrico.name',
    base: 'exp.acidoisocitrico.base',
    hight: 'exp.acidoisocitrico.hight',
    low: 'exp.acidoisocitrico.low',
  },
  {
    id: 11,
    name: 'exp.acido2ossoglutarico.name',
    base: 'exp.acido2ossoglutarico.base',
    hight: 'exp.acido2ossoglutarico.hight',
    low: 'exp.acido2ossoglutarico.low',
  },
  {
    id: 12,
    name: 'exp.acidosuccinico.name',
    base: 'exp.acidosuccinico.base',
    hight: 'exp.acidosuccinico.hight',
    low: 'exp.acidosuccinico.low',
  },
  {
    id: 13,
    name: 'exp.acidofumarico.name',
    base: 'exp.acidofumarico.base',
    hight: 'exp.acidofumarico.hight',
  },
  {
    id: 14,
    name: 'exp.acidomalico.name',
    base: 'exp.acidomalico.base',
    hight: 'exp.acidomalico.hight',
  },
  {
    id: 15,
    name: 'exp.acido2idrossiglutarato.name',
    base: 'exp.acido2idrossiglutarato.base',
    hight: 'exp.acido2idrossiglutarato.hight',
  },
  {
    id: 16,
    name: 'exp.acidoomovanillico.name',
    base: 'exp.acidoomovanillico.base',
    hight: 'exp.acidoomovanillico.hight',
    low: 'exp.acidoomovanillico.low',
  },
  {
    id: 17,
    name: 'exp.acidomanilvandelico.name',
    base: 'exp.acidomanilvandelico.base',
    hight: 'exp.acidomanilvandelico.hight',
    low: 'exp.acidomanilvandelico.low',
  },
  {
    id: 18,
    name: 'exp.hvavma.name',
    base: 'exp.hvavma.base',
    hight: 'exp.hvavma.hight',
  },
  {
    id: 19,
    name: 'exp.34diidrossifenilacetico.name',
    base: 'exp.34diidrossifenilacetico.base',
    hight: 'exp.34diidrossifenilacetico.hight',
    low: 'exp.34diidrossifenilacetico.low',
  },
  {
    id: 20,
    name: 'exp.triptofano.name',
    base: 'exp.triptofano.base',
    hight: 'exp.triptofano.hight',
    low: 'exp.triptofano.low',
  },
  {
    id: 21,
    name: 'exp.nacetil5idrossitriptamina.name',
    base: 'exp.nacetil5idrossitriptamina.base',
    hight: 'exp.nacetil5idrossitriptamina.hight',
    low: 'exp.nacetil5idrossitriptamina.low',
  },
  {
    id: 22,
    name: 'exp.serotonina.name',
    base: 'exp.serotonina.base',
    hight: 'exp.serotonina.hight',
    low: 'exp.serotonina.low',
  },
  {
    id: 23,
    name: 'exp.melatonina.name',
    base: 'exp.melatonina.base',
    hight: 'exp.melatonina.hight',
    low: 'exp.melatonina.low',
  },
  {
    id: 24,
    name: 'exp.acido5idrossindolacetico.name',
    base: 'exp.acido5idrossindolacetico.base',
    hight: 'exp.acido5idrossindolacetico.hight',
    low: 'exp.acido5idrossindolacetico.low',
  },
  {
    id: 25,
    name: 'exp.chinurenina.name',
    base: 'exp.chinurenina.base',
    hight: 'exp.chinurenina.hight',
    low: 'exp.chinurenina.low',
  },
  {
    id: 26,
    name: 'exp.acidochinurenico.name',
    base: 'exp.acidochinurenico.base',
    hight: 'exp.acidochinurenico.hight',
    low: 'exp.acidochinurenico.low',
  },
  {
    id: 27,
    name: 'exp.acidochinolinico.name',
    base: 'exp.acidochinolinico.base',
    hight: 'exp.acidochinolinico.hight',
    low: 'exp.acidochinolinico.low',
  },
  {
    id: 28,
    name: 'exp.triptamina.name',
    base: 'exp.triptamina.base',
    hight: 'exp.triptamina.hight',
    low: 'exp.triptamina.low',
  },
  {
    id: 29,
    name: 'exp.acidocitramalico.name',
    base: 'exp.acidocitramalico.base',
    hight: 'exp.acidocitramalico.hight',
  },
  {
    id: 30,
    name: 'exp.5idrossimetil2furancarbossilico.name',
    base: 'exp.5idrossimetil2furancarbossilico.base',
    hight: 'exp.5idrossimetil2furancarbossilico.hight',
  },
  {
    id: 31,
    name: 'exp.acidotartarico.name',
    base: 'exp.acidotartarico.base',
    hight: 'exp.acidotartarico.hight',
  },
  {
    id: 32,
    name: 'exp.furancarbonilglicina.name',
    base: 'exp.furancarbonilglicina.base',
    hight: 'exp.furancarbonilglicina.hight',
  },
  {
    id: 33,
    name: 'exp.acidotricarballilico.name',
    base: 'exp.acidotricarballilico.base',
    hight: 'exp.acidotricarballilico.hight',
  },
  {
    id: 34,
    name: 'exp.arabinosio.name',
    base: 'exp.arabinosio.base',
    hight: 'exp.arabinosio.hight',
  },
  {
    id: 35,
    name: 'exp.arabitolo.name',
    base: 'exp.arabitolo.base',
    hight: 'exp.arabitolo.hight',
  },
  {
    id: 36,
    name: 'exp.acido25furandicarbossilico.name',
    base: 'exp.acido25furandicarbossilico.base',
    hight: 'exp.acido25furandicarbossilico.hight',
  },
  {
    id: 37,
    name: 'exp.acido4idrossiippurico.name',
    base: 'exp.acido4idrossiippurico.base',
    hight: 'exp.acido4idrossiippurico.hight',
  },
  {
    id: 38,
    name: 'exp.acidoippurico.name',
    base: 'exp.acidoippurico.base',
    hight: 'exp.acidoippurico.hight',
    low: 'exp.acidoippurico.low',
  },
  {
    id: 39,
    name: 'exp.acidobenzoico.name',
    base: 'exp.acidobenzoico.base',
    hight: 'exp.acidobenzoico.hight',
  },
  {
    id: 40,
    name: 'exp.indacano.name',
    base: 'exp.indacano.base',
    hight: 'exp.indacano.hight',
  },
  {
    id: 41,
    name: 'exp.acido4idrossifenilacetico.name',
    base: 'exp.acido4idrossifenilacetico.base',
    hight: 'exp.acido4idrossifenilacetico.hight',
  },
  {
    id: 42,
    name: 'exp.acido3indoloacetico.name',
    base: 'exp.acido3indoloacetico.base',
    hight: 'exp.acido3indoloacetico.hight',
  },
  {
    id: 43,
    name: 'exp.pcresolo.name',
    base: 'exp.pcresolo.base',
    hight: 'exp.pcresolo.hight',
  },
  {
    id: 44,
    name: 'exp.3idrossifenilacetico.name',
    base: 'exp.3idrossifenilacetico.base',
    hight: 'exp.3idrossifenilacetico.hight',
  },
  {
    id: 45,
    name: 'exp.HPHPA.name',
    base: 'exp.HPHPA.base',
    hight: 'exp.HPHPA.hight',
  },
  {
    id: 46,
    name: 'exp.acidoglicolico.name',
    base: 'exp.acidoglicolico.base',
    hight: 'exp.acidoglicolico.hight',
  },
  {
    id: 47,
    name: 'exp.acidoglicerico.name',
    base: 'exp.acidoglicerico.base',
    hight: 'exp.acidoglicerico.hight',
  },
  {
    id: 48,
    name: 'exp.acidoossalico.name',
    base: 'exp.acidoossalico.base',
    hight: 'exp.acidoossalico.hight',
  },
  {
    id: 49,
    name: 'exp.acidopantotenico.name',
    base: 'exp.acidopantotenico.base',
    hight: 'exp.acidopantotenico.hight',
    low: 'exp.acidopantotenico.low',
  },
  {
    id: 50,
    name: 'exp.acidoglutarico.name',
    base: 'exp.acidoglutarico.base',
    hight: 'exp.acidoglutarico.hight',
  },
  {
    id: 51,
    name: 'exp.acidometilmalonico.name',
    base: 'exp.acidometilmalonico.base',
    hight: 'exp.acidometilmalonico.hight',
  },
  {
    id: 52,
    name: 'exp.nacetilcisteina.name',
    base: 'exp.nacetilcisteina.base',
    hight: 'exp.nacetilcisteina.hight',
  },
  {
    id: 53,
    name: 'exp.acidoascorbico.name',
    base: 'exp.acidoascorbico.base',
    hight: 'exp.acidoascorbico.hight',
    low: 'exp.acidoascorbico.low',
  },
  {
    id: 54,
    name: 'exp.acido4piridossico.name',
    base: 'exp.acido4piridossico.base',
    hight: 'exp.acido4piridossico.hight',
    low: 'exp.acido4piridossico.low',
  },
  {
    id: 55,
    name: 'exp.3idrossi3metilglutarico.name',
    base: 'exp.3idrossi3metilglutarico.base',
    hight: 'exp.3idrossi3metilglutarico.hight',
    low: 'exp.3idrossi3metilglutarico.low',
  },
  {
    id: 56,
    name: 'exp.uracile.name',
    base: 'exp.uracile.base',
    hight: 'exp.uracile.hight',
  },
  {
    id: 57,
    name: 'exp.timina.name',
    base: 'exp.timina.base',
    hight: 'exp.timina.hight',
  },
  {
    id: 58,
    name: 'exp.2idrossiippurico.name',
    base: 'exp.2idrossiippurico.base',
    hight: 'exp.2idrossiippurico.hight',
  },
  {
    id: 59,
    name: 'exp.acidoorotico.name',
    base: 'exp.acidoorotico.base',
    hight: 'exp.acidoorotico.hight',
  },
  {
    id: 60,
    name: 'exp.acidopiroglutammico.name',
    base: 'exp.acidopiroglutammico.base',
    hight: 'exp.acidopiroglutammico.hight',
    low: 'exp.acidopiroglutammico.low',
  },
  {
    id: 61,
    name: 'exp.acido2idrossibutirrico.name',
    base: 'exp.acido2idrossibutirrico.base',
    hight: 'exp.acido2idrossibutirrico.hight',
  },
  {
    id: 62,
    name: 'exp.acido4metil2ossovalerico.name',
    base: 'exp.acido4metil2ossovalerico.base',
    hight: 'exp.acido4metil2ossovalerico.hight',
  },
  {
    id: 63,
    name: 'exp.acidomandelico.name',
    base: 'exp.acidomandelico.base',
    hight: 'exp.acidomandelico.hight',
  },
  {
    id: 64,
    name: 'exp.acidoomogentisico.name',
    base: 'exp.acidoomogentisico.base',
    hight: 'exp.acidoomogentisico.hight',
  },
  {
    id: 65,
    name: 'exp.acido2idrossiisocaproico.name',
    base: 'exp.acido2idrossiisocaproico.base',
    hight: 'exp.acido2idrossiisocaproico.hight',
  },
  {
    id: 66,
    name: 'exp.acidoNacetilaspartico.name',
    base: 'exp.acidoNacetilaspartico.base',
    hight: 'exp.acidoNacetilaspartico.hight',
  },
  {
    id: 67,
    name: 'exp.acidomalonico.name',
    base: 'exp.acidomalonico.base',
    hight: 'exp.acidomalonico.hight',
  },
  {
    id: 68,
    name: 'exp.acido4idrossifenilpiruvico.name',
    base: 'exp.acido4idrossifenilpiruvico.base',
    hight: 'exp.acido4idrossifenilpiruvico.hight',
  },
  {
    id: 69,
    name: 'exp.acido2idrossi3metilbutirrico.name',
    base: 'exp.acido2idrossi3metilbutirrico.base',
    hight: 'exp.acido2idrossi3metilbutirrico.hight',
  },
  {
    id: 70,
    name: 'exp.creatinina.name',
    base: 'exp.creatinina.base',
    hight: 'exp.creatinina.hight',
    low: 'exp.creatinina.low',
  },
];
