export const UROGEN_NAMES = {
  '1': 'Lactobacillus crispatus',
  '2': 'Lactobacillus gasseri',
  '3': 'Lactobacillus iners',
  '4': 'Lactobacillus jensenii',
  '5': 'Candida albicans',
  '6': 'Candida dubliniensis',
  '7': 'Candida glabrata',
  '8': 'Candida krusei',
  '9': 'Candida lusitaniae',
  '10': 'Candida parapsilosis',
  '11': 'Candida tropicalis',
  '12': 'Clamydia trachomatis*',
  '13': 'Neisseria gonorrheae*',
  '14': 'Trichomonas vaginalis*',
  '15': 'Enterococcus faecalis',
  '16': 'Enterobacter cloacae complex',
  '17': 'Escherichia coli',
  '18': 'Gardnerella vaginalis',
  '19': 'Klebsiella aerogenes',
  '20': 'Klebsiella oxytoca',
  '21': 'Klebsiella pneumoniae',
  '22': 'Mycoplasma genitalium',
  '23': 'Mycoplasma hominis',
  '24': 'Proteus mirabilis',
  '25': 'Proteus vulgaris',
  '26': 'Pseudomonas aeruginosa',
  '27': 'Serratia marcescens',
  '28': 'Staphylococcus aureus',
  '29': 'Staphylococcus saprophyticus',
  '30': 'Ureoplasma parvum',
  '31': 'Ureoplasma urealyticum',
  '48': 'Caspofun (CAS 5 μg)',
  '49': 'Fluconazole (FLU 25 μg)',
  '50': 'Posoconazole (POS 5 μg)',
  '51': 'Voriconazole (VO 1 μg)3',
  '52': 'Amphotericin (AMB 20 μg)',
  '53': 'Ketokonazole (KCA 10 μg)',
  '54': 'Flucytosine (AFY 1 μg)',
  '55': 'Nystatin (NY 100 μg)',
  '56': 'Tetracyclina (TE 8 μg/ml)',
  '57': 'Pefloxacin (PEF 16 μg/ml)',
  '58': 'Ofloxacin (OFX 4 μg/ml)',
  '59': 'Doxyciclin (DO 8 μg/ml)',
  '60': 'Erythromycin (E 16 μg/ml)',
  '61': 'Clarithromycin (CLA 16 μg/ml)',
  '62': 'Minocycline (MN 8 μg/ml)',
  '63': 'Josamycin (JOS 8 μg/ml)',
  '64': 'Clindamycin (CD 8 μg/ml)',
  '65': 'Cannella',
  '66': 'Njauli',
  '67': 'Salvia',
  '68': 'Ginepro',
  '69': 'Cajeput',
  '70': 'Chiodi di garofano',
  '71': 'Lavanda',
  '72': 'Santoreggia',
  '73': 'Melissa',
  '74': 'Rosmarino',
  '75': 'Origano',
  '76': 'Pino silvestre',
  '77': 'Melaleuca',
  '78': 'Eucalipto',
  '79': 'Timo',
  '80': 'Zenzero',
  '81': 'Ciprofloxacin (CIP 5 μg)',
  '82': 'Doxycicline (DXT 30 μg)',
  '83': 'Fosfomycin (FOS 50 μg)',
  '84': 'Levofloxacin (LEV 5 μg)',
  '85': 'Metronidazole (MTZ 50 μg)',
  '86': 'Moxifloxacin (MXF 5 μg)',
  '87': 'Nitrofurantoin (F 100 μg)',
  '88': 'Trimethoprim-Sulfamethoxa',
  '89': 'Cefoxitin (FOX 30  µg)',
  '90': 'Levofloxacin (LEV 5 µg)',
  '91': 'Netilmicin (NET 10  µg )',
  '92': 'Tetracycline ( TE 30  µg)',
  '93': 'Erythromycin (ERY 15  µg)',
  '94': 'Gentamycin (CN 10  µg)',
  '95': 'Rifampicin (RD 5  µg)',
  '96': 'Linezolid (LNZ 10  µg)',
};

export const UROGEN_DESC = {
  '1': 'La specie più protettiva: produce grandi quantità di acido D-lattico e perossido di idrogeno (H₂O₂). La sua presenza in abbondanza è associata al minor rischio di infezioni.',
  '2': 'Seconda specie per efficacia protettiva; frequente nelle donne in età fertile. Contribuisce attivamente al mantenimento del pH acido.',
  '3': 'Specie diffusa ma meno protettiva delle precedenti. In condizioni di stress o antibioticoterapia può persistere anche quando le altre specie diminuiscono.',
  '4': "Specie meno comune, anch'essa produttrice di perossido di idrogeno. Una sua presenza stabile è comunque un indicatore positivo di flora equilibrata.",
  '5': 'La specie più comune e frequente causa di candidosi vulvovaginale. Generalmente sensibile agli antimicotici di prima linea.',
  '6': 'Specie strettamente correlata a C. albicans, con cui può essere confusa. Può manifestare resistenza al fluconazolo.',
  '7': "Specie a ridotta sensibilità agli azolici, in aumento nelle candidosi recidivanti. Richiede spesso l'uso di antimicotici alternativi.",
  '8': 'Specie intrinsecamente resistente al fluconazolo. La sua identificazione è clinicamente rilevante per orientare la terapia antimicotica.',
  '9': "Specie rara ma clinicamente significativa per la sua potenziale resistenza all'amfotericina B. Richiede test di sensibilità mirati.",
  '10': 'Specie opportunista frequente in soggetti immunocompromessi. Generalmente sensibile agli azolici ma con sensibilità ridotta alle echinocandine.',
  '11': 'Specie emergente associata a forme più aggressive di candidosi. Può sviluppare resistenza agli azolici in caso di esposizione prolungata.',
  '12': "L'infezione sessualmente trasmessa batterica più diffusa al mondo. Spesso asintomatica, può causare malattia infiammatoria pelvica e infertilità se non trattata.",
  '13': 'Batterio responsabile della gonorrea. Causa secrezioni purulente, bruciore e, nelle forme trascurate, complicanze riproduttive.',
  '14': 'Protozoo responsabile della tricomoniasi, infezione sessualmente trasmessa molto comune. Può causare vaginiti con perdite schiumose e maleodoranti.',
  '15': "Batterio commensale dell'intestino che può colonizzare il tratto urinario, causando cistiti e, in soggetti predisposti, infezioni ricorrenti difficili da eradicare.",
  '16': 'Enterobatterio opportunista, spesso resistente a più antibiotici.',
  '17': 'Principale causa di infezioni urinarie; può colonizzare la vagina e favorire recidive.',
  '18': 'Batterio strettamente correlato alla vaginosi batterica (VB), la causa più frequente di perdite vaginali anomale.',
  '19': 'Enterobatterio opportunista che può causare infezioni urinarie e vaginiti.',
  '20': 'Enterobatterio opportunista che può causare infezioni urinarie e vaginiti.',
  '21': 'Batterio ospedaliero noto per la sua alta resistenza agli antibiotici.',
  '22': 'Patogeno emergente associato a cervicite, uretrite e malattia infiammatoria pelvica (MIP).',
  '23': 'Può contribuire a vaginosi batterica e complicanze in gravidanza.',
  '24': 'Associato a infezioni urinarie ricorrenti; produce ureasi, alcalinizza le urine e favorisce la formazione di calcoli renali.',
  '25': 'Associato a infezioni urinarie ricorrenti; produce ureasi, alcalinizza le urine e favorisce la formazione di calcoli renali.',
  '26': 'Batterio opportunista: la sua presenza è rara, ma clinicamente rilevante.',
  '27': 'Microrganismo ambientale, occasionalmente patogeno nelle infezioni urinarie.',
  '28': 'Batterio potenzialmente patogeno in grado di colonizzare il tratto urogenitale. Alcune varianti producono tossine e possono causare infezioni localizzate o sistemiche.',
  '29': 'Seconda causa più frequente di cistiti nelle donne giovani sessualmente attive, dopo Escherichia coli.',
  '30': 'Colonizzatore frequente del tratto genitale; può essere rilevante in gravidanza o in soggetti immunocompromessi.',
  '31': 'Associato a uretrite e complicanze in gravidanza se presente in cariche elevate.',
};
