export const VLSCFA_NAMES = {
  '1': 'acido acetico',
  '2': 'acido propionico',
  '3': 'acido iso-butirrico',
  '4': 'acido butirrico',
  '5': 'acido 2-metil-butirrico',
  '6': 'acido iso-valerico',
  '7': 'acido valerico',
  '8': 'acido caproico',
  '9': 'acido eptanoico',
  '10': 'indacano*',
  '11': 'p-cresolo',
  '12': 'acido benzoico',
  '13': 'acido 4-idrossifenilacetico',
  '14': 'acido 3-idrossifenilacetico',
  '15': 'acido lattico',
  '16': 'acido furan-2,5-dicarbossilico',
  '17': 'o-cresolo',
  '18': 'm-cresolo',
  '19': 'creatinina*',
};
