export const VLSCFA_EXPLANATIONS = [
  {
    id: 0,
    title: 'pdfpages.vlscfatable.groups.0.sectiontitle1',
    title2: 'pdfpages.vlscfatable.groups.0.sectiontitle2',
    general: null,
    metaIds: '1-9',
  },
  {
    id: 1,
    title: 'pdfpages.vlscfatable.groups.0.sectiontitle1',
    title2: 'pdfpages.vlscfatable.groups.0.sectiontitle1',
    general: null,
    metaIds: '10-19',
  },
];

export const VLSCFA_ELEMENTS_EXP = [
  {
    id: 1,
    name: 'exp.vlsfca.1.name',
    base: 'exp.vlsfca.1.base',
    hight: 'exp.vlsfca.1.hight',
    low: 'exp.vlsfca.1.low',
  },
  {
    id: 2,
    name: 'exp.vlsfca.2.name',
    base: 'exp.vlsfca.2.base',
    hight: 'exp.vlsfca.2.hight',
    low: 'exp.vlsfca.2.low',
  },
  {
    id: 3,
    name: 'exp.vlsfca.3.name',
    base: 'exp.vlsfca.3.base',
    hight: 'exp.vlsfca.3.hight',
    low: 'exp.vlsfca.3.low',
  },
  {
    id: 4,
    name: 'exp.vlsfca.4.name',
    base: 'exp.vlsfca.4.base',
    hight: 'exp.vlsfca.4.hight',
    low: 'exp.vlsfca.4.low',
  },
  {
    id: 5,
    name: 'exp.vlsfca.5.name',
    base: 'exp.vlsfca.5.base',
    hight: 'exp.vlsfca.5.hight',
    low: 'exp.vlsfca.5.low',
  },
  {
    id: 6,
    name: 'exp.vlsfca.6.name',
    base: 'exp.vlsfca.6.base',
    hight: 'exp.vlsfca.6.hight',
    low: 'exp.vlsfca.6.low',
  },
  {
    id: 7,
    name: 'exp.vlsfca.7.name',
    base: 'exp.vlsfca.7.base',
    hight: 'exp.vlsfca.7.hight',
    low: 'exp.vlsfca.7.low',
  },
  {
    id: 8,
    name: 'exp.vlsfca.8.name',
    base: 'exp.vlsfca.8.base',
    hight: 'exp.vlsfca.8.hight',
    low: 'exp.vlsfca.8.low',
  },
  {
    id: 9,
    name: 'exp.vlsfca.9.name',
    base: 'exp.vlsfca.9.base',
    hight: 'exp.vlsfca.9.hight',
    low: 'exp.vlsfca.9.low',
  },
  {
    id: 10,
    name: 'exp.vlsfca.10.name',
    base: 'exp.vlsfca.10.base',
    hight: 'exp.vlsfca.10.hight',
    low: 'exp.vlsfca.10.low',
  },
  {
    id: 11,
    name: 'exp.vlsfca.11.name',
    base: 'exp.vlsfca.11.base',
    hight: 'exp.vlsfca.11.hight',
    low: 'exp.vlsfca.11.low',
  },
  {
    id: 12,
    name: 'exp.vlsfca.12.name',
    base: 'exp.vlsfca.12.base',
    hight: 'exp.vlsfca.12.hight',
    low: 'exp.vlsfca.12.low',
  },
  {
    id: 13,
    name: 'exp.vlsfca.13.name',
    base: 'exp.vlsfca.13.base',
    hight: 'exp.vlsfca.13.hight',
    low: 'exp.vlsfca.13.low',
  },
  {
    id: 14,
    name: 'exp.vlsfca.14.name',
    base: 'exp.vlsfca.14.base',
    hight: 'exp.vlsfca.14.hight',
    low: 'exp.vlsfca.14.low',
  },
  {
    id: 15,
    name: 'exp.vlsfca.15.name',
    base: 'exp.vlsfca.15.base',
    hight: 'exp.vlsfca.15.hight',
    low: 'exp.vlsfca.15.low',
  },
  {
    id: 16,
    name: 'exp.vlsfca.16.name',
    base: 'exp.vlsfca.16.base',
    hight: 'exp.vlsfca.16.hight',
    low: 'exp.vlsfca.16.low',
  },
  {
    id: 17,
    name: 'exp.vlsfca.17.name',
    base: 'exp.vlsfca.17.base',
    hight: 'exp.vlsfca.17.hight',
  },
  {
    id: 18,
    name: 'exp.vlsfca.18.name',
    base: 'exp.vlsfca.18.base',
    hight: 'exp.vlsfca.18.hight',
  },
];
